### ISSUE TITLE
Incorrect state graph

### ISSUE THREAD

**Issue by hypeartist** [codewitch-honey-crisis/VisualFA#1]
Pattern `(0|([1-9][0-9]*))(\.[0-9]+)?`
Input: `002`

Resulting optimized DFA graph:
![image](https://github.com/codewitch-honey-crisis/VisualFA/assets/3519388/0ceb3dae-2f2d-4844-b160-d95478ea01f3)

While pattern without optional fractional part: `0|([1-9][0-9]*)`, results in correct graph without any match:
![image](https://github.com/codewitch-honey-crisis/VisualFA/assets/3519388/a906b947-f9da-4540-9071-7421bcf473e2)

**Comment by codewitch-honey-crisis** [comment]
Thanks. I'll look into it. I think it's a regression in my Parse() methods. Edit: I'm investigating now. Thought the problem was in my parse code but it's not.

**Comment by codewitch-honey-crisis** [comment]
I went ahead and pushed because I believe it's fixed. Please let me know if you run into more trouble with it. I'm running more manual testing on it now but I wanted to get this to you.
